### ISSUE TITLE
specificity computation

### ISSUE THREAD

**Issue by arahuja** [hammerlab/variant-calling-benchmarks#18]
Looking in `joint_caller.py` the specificity computation is 

```
merged.ix[merged.called_guacamole][called_col]
```

This seems like this computes the number of true calls / number of calls made by guacamole - is that's what intended? Should this be precision then or do I have that wrong?

**Comment by timodonnell** [comment]
Woah I think you found a bug in my brain. Since sensitivity and recall are synonyms I had somehow come to believe that specificity and precision also were the same. Thanks for spotting this!
